Improve manifest information
SAP-samples/ui5-typescript-walkthrough pull request #93
Opened 2024-12-05 10:50 UTC by margopolo

Fix terminology, update information on relation between manifest version and OpenUI5 version.

2024-12-20 15:51 UTC, Thodd commented on steps/10/README.md
> +    > It is crucial to be mindful of the lazy loading configuration for libraries. Only libraries that are absolutely necessary for your component to start should be declared with `"lazy": false`. Fo
LGTM. Should we add a link to the [`Lib.load`](https://ui5.sap.com/#/api/sap.ui.core.Lib%23methods/sap.ui.core.Lib.load) documentation here?

maybe something like this?

> Before using a library marked with `"lazy": true`, you need to ensure that it is loaded by calling the asynchronous [`Lib.load`](https://ui5.sap.com/#/api/sap.ui.core.Lib%23methods/sap.ui.core.Lib.load) API. A usage example can be found in the linked API reference.

2025-01-13 16:36 UTC, KlattG requested changes

2025-01-13 16:36 UTC, KlattG commented on steps/01/README.md
> +Since we want the app we build to supports not only the latest OpenUI5 version but also the latest long-term version, which is OpenUI5 1.120, we set the descriptor format version to `1.60.0`.
```suggestion
Since we want our app to support not the latest OpenUI5 version but rather the latest long-term maintenance version, which is OpenUI5 1.120, we set the format version to `1.60.0`.
```

2025-01-13 16:36 UTC, KlattG commented on steps/01/README.md
> +    -   `id`: This specifies an identifier for the application using dot notation, limited to 70 characters. It must be unique and must correspond to the component ID/namespace.
```suggestion
    -   `id`: This specifies an identifier for the application. It is provided in dot notation and is limited to 70 characters. It must be unique and must correspond to the component ID/namespace.
```

2025-01-13 16:36 UTC, KlattG commented on steps/01/README.md
> +    -   `type`: This property helps in identify whether the project is an `application` or `component`. Including it provides a useful classification and assists in the correct loading of the applica
```suggestion
    -   `type`: This property helps to identify whether the project is an `application` or a `component`. It provides a useful classification and assists in the correct loading of the application.
```

2025-01-13 16:36 UTC, KlattG commented on steps/10/README.md
> +All application-specific configuration settings will now further be put into the manifest. This clearly separates the application coding from the configuration settings and makes our app even more fl
```suggestion
All application-specific configuration settings will now be put into the manifest. This clearly separates the application coding from the configuration settings and makes our app even more flexible.
```

2025-01-13 16:36 UTC, KlattG commented on steps/10/README.md
> +> Properties of the resource bundle are enclosed in two curly brackets in the manifest. This is not an OpenUI5 data binding syntax, but a variable reference to the resource bundle in the manifest in
```suggestion
> Properties of the resource bundle are enclosed in two curly brackets in the manifest. This is not an OpenUI5 data binding syntax but a variable reference to the resource bundle in the manifest in handlebars syntax.
```

2025-01-13 16:36 UTC, KlattG commented on steps/10/README.md
> +-   `technology` \(mandatory\): This property specifies the technology used for the application; the value is `UI5`.
```suggestion
-   `technology` \(mandatory\): This property specifies the technology used for the application; its value must be `UI5`.
```

2025-01-13 16:36 UTC, KlattG commented on steps/10/README.md
> +    In our component we are currenetly only using the two libraries `sap.ui.core` and `sap.m`. The `sap.ui.core` library provides the basic framework functionality and is required for any OpenUI5 app
```suggestion
    In our component, we currently only use the `sap.ui.core` and `sap.m` libraries. The `sap.ui.core` library provides the basic framework functionality and is required for any OpenUI5 application.<br>
```

2025-01-13 16:36 UTC, KlattG commented on steps/10/README.md
> +-   The manifest file is named `manifest` and stored as JSON file.
```suggestion
-   The manifest file is named `manifest` and stored as a JSON file.
```

2025-01-13 16:51 UTC, petermuessig submitted a review, later dismissed
Just some minor comments

2025-01-13 16:51 UTC, petermuessig commented on steps/01/README.md
> +  To find the appropriate `_version` for each OpenUI5 release, refer to [Descriptor for Applications, Components, and Libraries \(manifest.json\)](https://sdk.openui5.org/topic/be0cf40f61184b358b5fae
Just FYI: the information is also available here: https://github.com/SAP/ui5-manifest/blob/main/mapping.json

2025-01-13 16:51 UTC, petermuessig commented on steps/01/README.md
> +    -   `type`: This property helps in identify whether the project is an `application` or `component`. Including it provides a useful classification and assists in the correct loading of the applica
To be precise, it can be also "library" or "card"

2025-01-17 14:37 UTC, petermuessig approved these changes
LGTM

2025-01-17 14:37 UTC, petermuessig commented on steps/01/README.md
> +  To find the appropriate `_version` for each OpenUI5 release, refer to [Descriptor for Applications, Components, and Libraries \(manifest.json\)](https://sdk.openui5.org/topic/be0cf40f61184b358b5fae
The name of the topic in the documentation will be also adopted in the future to manifest, right?

2025-01-17 19:52 UTC, margopolo commented on steps/01/README.md
> +  To find the appropriate `_version` for each OpenUI5 release, refer to [Descriptor for Applications, Components, and Libraries \(manifest.json\)](https://sdk.openui5.org/topic/be0cf40f61184b358b5fae
Just checked and this is currently the title of the chapter.
@KlattG let us know in case this is changed.

2025-01-17 19:53 UTC, merged

2025-01-20 11:04 UTC, KlattG commented on steps/01/README.md
> +  To find the appropriate `_version` for each OpenUI5 release, refer to [Descriptor for Applications, Components, and Libraries \(manifest.json\)](https://sdk.openui5.org/topic/be0cf40f61184b358b5fae
The topic has recently been renamed to "Manifest (Descriptor for Applications, Components, and Libraries)".
I hope that's fine with you.