chore: update to UI5 version 1.131.1
SAP-samples/ui5-typescript-walkthrough pull request #96
Opened 2024-12-17 14:34 UTC by matz3

2025-01-16 08:14 UTC, flovogt commented on steps/05/package.json
> +    "@types/openui5": "^1.131.0",
@matz3 @akudev There is a openui5 version `1.131.1` but no patch release for the types. So this means, there were no change in regards to types, right?

2025-01-16 09:09 UTC, akudev commented on steps/05/package.json
> +    "@types/openui5": "^1.131.0",
@flovogt no, for @types/openui5, the release process is manual and quite some effort, so we do in general not release any patches. Only in rare exceptions.
For @openui5/types, on the other hand, the types are released ALWAYS as part of the release process, regardless of any changes.

2025-01-16 12:58 UTC, flovogt commented on steps/05/package.json
> +    "@types/openui5": "^1.131.0",
Thanks @akudev. I am in favour of migrating the project to `@openui5/types` . Then its also easier to switch to the `@sapui5/types`. Whats your opinion? @akudev @petermuessig

2025-02-10 13:15 UTC, flovogt commented
I have updated the PR to reflect the usage of the current latest UI5 version. 

The migration of `@types/openui5` to `@openui5/types` will be done in a separate PR

2025-02-10 13:38 UTC, akudev submitted a review, later dismissed

2025-02-10 13:40 UTC, margopolo commented on steps/01/README.md
> +-   The `_version` attribute is a mandatory field in the app descriptor that indicates the format version of the descriptor. This attribute is crucial for identifying application settings when the de
You are still using the outdated term "app descriptor" here. I would recommend to keep the original description instead. Also, you mention here that with 1.132 we need to specify the manifest version 1.68.0 but in fact in the below json code snippet (as well as in the sure files) it says 1.60.

2025-02-10 13:42 UTC, margopolo requested changes
In step 01, readme you are still using the outdated term "app descriptor". Also the manifest is not updated to 1.68 as explained in the text.

2025-02-10 14:36 UTC, flovogt commented on steps/01/README.md
> +-   The `_version` attribute is a mandatory field in the app descriptor that indicates the format version of the descriptor. This attribute is crucial for identifying application settings when the de
Good catch! Thx Margot. I have reset the readme in step 01 to the current version. The initial update on this file is already covered by your PR few weeks back.

2025-02-10 19:00 UTC, merged